# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de1dbc70200caccedb5cd902283d5f9f89651130afa0818afae46972cb2bc5ab089ba0054be9d9887aa38aca1cd25830756b27b6717ef4a46a2d22e31c59d6e8

test:
  secret_key_base: e206d96f0d33a4643ef9afcaeb06e02a429cc41bd2fe64c49a6b45528293a29771151ff51f1827944a12710bad0d9ae24d0c538009e0a6cfb7f9408d9b06b129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
